import { Header } from "components/components/header/Header";
import { Footer } from "components/components/footer/Footer";
import { Box, Stack } from "@mui/material";
import "./styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Stack height="100%">
          <Header />
          <Box p={2} flex={1}>
            {children}
          </Box>
          <Footer />
        </Stack>
      </body>
    </html>
  );
}
